################################################################################
# Copyright (c) 2022, NVIDIA CORPORATION. All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
################################################################################

# tiled-display:
#   enable: 1
#   rows: 2
#   columns: 2
# width=2560
# height=1440
# gpu-id=0
#(0): nvbuf-mem-default - Default memory allocated, specific to particular platform
#(1): nvbuf-mem-cuda-pinned - Allocate Pinned/Host cuda memory, applicable for Tesla
#(2): nvbuf-mem-cuda-device - Allocate Device cuda memory, applicable for Tesla
#(3): nvbuf-mem-cuda-unified - Allocate Unified cuda memory, applicable for Tesla
#(4): nvbuf-mem-surface-array - Allocate Surface Array memory, applicable for Jetson
# nvbuf-memory-type=0

# source0:
#   enable: 1
#   type: 1
#   camera-id: 0
#   camera-width: 1920
#   camera-height: 1080
#   camera-fps-n: 30
#   camera-fps-d: 1
#   video-format: I420
#   camera-v4l2-dev-node: 0
#   cudadec-memtype: 0

# source1:
#   enable: 1
#   type: 1
#   camera-id: 1
#   camera-width: 1920
#   camera-height: 1080
#   camera-fps-n: 30
#   camera-fps-d: 1
#   video-format: I420
#   camera-v4l2-dev-node: 1
#   cudadec-memtype: 0

source-list:
  # semicolon separated uri. For ex- uri1;uri2;uriN;
  # list: file:///opt/nvidia/deepstream/deepstream/samples/streams/sample_1080p_h264.mp4;
  list: file:/home/orin/Downloads/vi.mp4;file:/home/orin/Downloads/ir.mp4;
  # list: rtsp://192.168.1.106:18554/vi;rtsp://192.168.1.106:28554/ir;
  # list: http://192.168.1.167/2.ts;http://192.168.1.168/2.ts;



streammux:
  gpu-id: 0
  batch-size: 2
  batched-push-timeout: 40000
  # width: 1024
  # height: 768
  width: 640
  height: 512
  # sync-inputs: 1
  # live-source: 1
# preprocess0:
#   enable: 1
#   config-file-path: config_preprocess_RGBT.txt

# preprocess1:
#   enable: 1
#   config-file-path: config_preprocess_RGBT1.txt

streammux-b0:
  gpu-id: 0
  batch-size: 2
  batched-push-timeout: 40000
  width: 640
  height: 512
  sync-inputs: 1
  # live-source: 1


streammux-b1:
  gpu-id: 0
  batch-size: 2
  batched-push-timeout: 40000
  width: 640
  height: 512
  sync-inputs: 1
  # live-source: 1


osd:
  process-mode: 1
  display-text: 1
  display-bbox: 1

tiler:
  rows: 2
  columns: 2
  width:  1920
  height: 1080

sink:
  qos: 0
  sync: 0

# Inference using nvinfer:
primary-gie-0:
  plugin-type: 0
  batch-size: 2
  unique-id: 1
  # raw-output-file-write: 1
  # bbox-border-color0: 1;0;0;1
  # bbox-border-color1: 0;1;1;1
  # bbox-border-color2: 0;0;1;1
  # bbox-border-color3: 0;1;0;1
  config-file-path: rgbt_pgie_config.yml

primary-gie-1:
  plugin-type: 0
  batch-size: 2
  unique-id: 2
  # bbox-border-color0: 1;0;0;1
  # bbox-border-color1: 0;1;1;1
  # bbox-border-color2: 0;0;1;1
  # bbox-border-color3: 0;1;0;1
  config-file-path: rgbt_sgie_config.yml


metamux:
  config-file-path: config_metamux3.txt
# post-process:
#   postprocesslib-name: postprocesslib_impl/libpostprocess_impl.so
#   postprocesslib-config-file: config_postprocess_RGBT.yml

# video-template:
#   customlib-name: ./videotemplatelib_impl/libcustom_videoimpl.so
#   customlib-props: add-fusion-surface:1

## Inference using nvinferserver:
#primary-gie:
#  plugin-type: 1
#  config-file-path: dstest3_pgie_nvinferserver_config.txt
